// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Command
	Reply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CommandId int32

const (
	CommandId_PING    CommandId = 0
	CommandId_SET     CommandId = 1
	CommandId_GET     CommandId = 2
	CommandId_DEL     CommandId = 3
	CommandId_CGET    CommandId = 4
	CommandId_CADD    CommandId = 5
	CommandId_EXPIRE  CommandId = 6
	CommandId_TTL     CommandId = 7
	CommandId_PERSIST CommandId = 8
)

var CommandId_name = map[int32]string{
	0: "PING",
	1: "SET",
	2: "GET",
	3: "DEL",
	4: "CGET",
	5: "CADD",
	6: "EXPIRE",
	7: "TTL",
	8: "PERSIST",
}
var CommandId_value = map[string]int32{
	"PING":    0,
	"SET":     1,
	"GET":     2,
	"DEL":     3,
	"CGET":    4,
	"CADD":    5,
	"EXPIRE":  6,
	"TTL":     7,
	"PERSIST": 8,
}

func (x CommandId) Enum() *CommandId {
	p := new(CommandId)
	*p = x
	return p
}
func (x CommandId) String() string {
	return proto.EnumName(CommandId_name, int32(x))
}
func (x *CommandId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandId_value, data, "CommandId")
	if err != nil {
		return err
	}
	*x = CommandId(value)
	return nil
}
func (CommandId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Command struct {
	CommandId        *CommandId `protobuf:"varint,1,req,name=commandId,enum=protocol.CommandId" json:"commandId,omitempty"`
	Args             []string   `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetCommandId() CommandId {
	if m != nil && m.CommandId != nil {
		return *m.CommandId
	}
	return CommandId_PING
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type Reply struct {
	Values           []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Error            *string  `protobuf:"bytes,2,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Reply) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "protocol.Command")
	proto.RegisterType((*Reply)(nil), "protocol.Reply")
	proto.RegisterEnum("protocol.CommandId", CommandId_name, CommandId_value)
}

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8c, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x40, 0xdd, 0xf4, 0x23, 0xcd, 0xa8, 0x25, 0x8c, 0x97, 0x3d, 0x2e, 0x7b, 0x58, 0x8a, 0x87,
	0x1e, 0xfc, 0x03, 0x22, 0x6d, 0x58, 0x02, 0x8b, 0x94, 0x36, 0x07, 0xaf, 0x61, 0x37, 0xee, 0xa5,
	0x35, 0x25, 0x51, 0xc1, 0x7f, 0x6f, 0x52, 0x29, 0x9e, 0xe6, 0x31, 0xef, 0xcd, 0x40, 0x39, 0x19,
	0xef, 0xf5, 0xd5, 0xf8, 0x7a, 0x76, 0xf6, 0xd3, 0x62, 0xb1, 0x8c, 0xb3, 0x1d, 0xf7, 0xcf, 0x40,
	0x1b, 0x3b, 0x4d, 0xfa, 0xe3, 0x82, 0x07, 0x60, 0xe7, 0x3f, 0x94, 0x97, 0xed, 0x66, 0x47, 0xaa,
	0xf2, 0xe9, 0xa1, 0x5e, 0xc3, 0xba, 0x59, 0x15, 0xde, 0x41, 0xaa, 0xdd, 0xd5, 0x6f, 0xc9, 0x2e,
	0xa9, 0xd8, 0xfe, 0x00, 0x59, 0x6f, 0xe6, 0xf1, 0x07, 0x4b, 0xc8, 0xbf, 0xf5, 0xf8, 0x65, 0x7c,
	0xb8, 0x0d, 0x02, 0xef, 0x21, 0x33, 0xce, 0x59, 0x17, 0x3a, 0x52, 0xb1, 0xc7, 0x77, 0x60, 0xff,
	0x2f, 0x0a, 0x48, 0x3b, 0xf9, 0x7a, 0xe4, 0x37, 0x48, 0x21, 0x19, 0x84, 0xe2, 0x9b, 0x08, 0xc7,
	0x00, 0x24, 0x42, 0x2b, 0x4e, 0x3c, 0x89, 0x51, 0x13, 0x57, 0xe9, 0x42, 0x2f, 0x6d, 0xcb, 0x33,
	0x04, 0xc8, 0xc5, 0x5b, 0x27, 0x7b, 0xc1, 0xf3, 0x18, 0x2a, 0x75, 0xe2, 0x14, 0x6f, 0x81, 0x76,
	0xa2, 0x1f, 0xe4, 0xa0, 0x78, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xc0, 0x82, 0xc7, 0xeb,
	0x00, 0x00, 0x00,
}
